site_name: j6n | docs
site_url: https://docs.j6n.ca
repo_url: https://github.com/j6nca/docs
repo_name: j6nca/docs
copyright: Copyright &copy; 2024 Jonathan Ng
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/j6nca
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/j6n
    - icon: fontawesome/brands/discord 
      link: https://discordapp.com/users/189118524784902146
theme:
  name: material
  logo: assets/logo.gif
  favicon: assets/favicon.ico
  palette: 
  
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
plugins:
  # - meta
  # - blog
  - search
  - tags:
      tags_file: tags.md
      # tags_slugify: !!python/object/apply:pymdownx.slugs.slugify
      #   kwds:
      #     case: lower
      # tags_allowed:
      #   - cooking
      #   - projects
  - git-revision-date-localized:
      enable_creation_date: true
      timezone: Canada/Eastern
      type: datetime
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

# nav:
#   - Projects: "index.md"
#   - Cooking: "index.md"
