site_name: My Notes
site_url: https://notes.j6n.ca
repo_url: https://github.com/j6nca/docs
repo_name: j6nca/notes
copyright: Copyright &copy; 2024 Jonathan Ng
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/j6nca
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/j6n
    - icon: fontawesome/brands/discord 
      link: https://discordapp.com/users/189118524784902146
theme:
  name: material
  logo: assets/logo.gif
  favicon: assets/favicon.ico
  palette: 
  
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
plugins:
  # - meta
  # - blog
  - search
  - tags:
      tags_file: tags.md
      # tags_slugify: !!python/object/apply:pymdownx.slugs.slugify
      #   kwds:
      #     case: lower
      # tags_allowed:
      #   - cooking
      #   - projects
  - git-revision-date-localized:
      enable_creation_date: true
      timezone: Canada/Eastern
      type: datetime
  - callouts
  - glightbox
  # - ezlinks
  - obsidian-interactive-graph
  # - obsidian-support
  - obsidian-bridge
  
extra_css:
  - assets/stylesheets/obsidian_tags.css
  - assets/stylesheets/interactive_graph.css

extra_javascript:
  - https://fastly.jsdelivr.net/npm/jquery/dist/jquery.min.js
  - https://fastly.jsdelivr.net/npm/echarts/dist/echarts.min.js
  - assets/javascripts/obsidian_tags.js
  - assets/javascripts/interactive_graph.js
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences

# nav:
#   - Home: "index.md"
#   - Food: "food/index.md"
#   - Keyboards: "keyboards/index.md"
#   - Learning: "learning/index.md"


draft_docs: |
  drafts/

exclude_docs: |